### ISSUE TITLE
Why is there a "\" here?

### ISSUE THREAD

**Issue by tagptroll1** [HuyaneMatsu/discord_uwu#1]
https://github.com/HuyaneMatsu/discord_uwu/blob/37b301ec38c367550cee6357807ee77134f91d16/message.py#L485

The \ here is redundant.

**Comment by HuyaneMatsu** [comment]
There is almost everywhere "\" after "[", "(", "{". I like to make it clean, if something continues at the next line, even if it is unnecesarry.

**Comment by HuyaneMatsu** [comment]
Issue resolved with the new [commit](https://github.com/HuyaneMatsu/discord_uwu/commit/1192164630527b6bb5535c3d2a2ab7295da32a3c).
